name: Ilgiglionelcuore
favicon: null
layout_spectrum: 0.5342748174443841
typography_spectrum: 0.9859006404876709
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf1df'
    - '#4c87d5'
    - '#a2caee'
    - '#144182'
    - '#a9a0a6'
  brandStrength: 0.6647108704783022
  lightness: 0.872982774162665
  saturation: 0.8424490967299789
  rhythmicContrast: 0.39269269723445177
purpose: []
