name: Ilgiglionelcuore
favicon: null
layout_spectrum: 0.17878364282660186
typography_spectrum: 0.29992109909653664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf1df'
    - '#4c87d5'
    - '#a2caee'
    - '#144182'
    - '#a9a0a6'
  brandStrength: 0.4535139803774655
  lightness: 0.8041559264529496
  saturation: 0.01133245462551713
  rhythmicContrast: 0.3572923308238387
purpose: []
